### PR TITLE
Use submenus for context menu items

### PR DESCRIPTION
**Pull request by johanhammar**
Use submenus for context menu items and change the default to have the new submenu enabled by default.

### CODE REVIEW

**Comment by johanhammar** [comment]
This is what it looks like
image

**Comment by johanhammar** [comment]
Submenus where introduced in [VSCode 1.50, september release.](https://code.visualstudio.com/updates/v1_50#_submenus)

I am not sure how the extension works on older releases

**Comment by johanhammar** [comment]
Thinking about it, we should probably also remove the editorHasSelection condition to better match how the command pallette invocation works?

**Review by jrebocho — CHANGES_REQUESTED** [review]
Thanks for the contribution @johanhammar ! I agree, probably we should remove the `editorHasSelection` like you suggested.

**Comment by johanhammar** [comment]
Fixed

**Review by jrebocho — APPROVED** [review]
Great work 🚀 Thanks for the improvement!

**Pull request merged**
